---
- name: Apache server installed
  hosts: apache

  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: deploy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
    notify: Restart Apache

handlers:
    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted