---
- name: Install DHCP Server
  hosts: dhcp
  become: yes

  tasks:
    - name: Install DHCP packages
      yum:
        name: dhcp-server
        state: present

    - name: Copy CSV File
      copy:
        src: hosts.csv
        dest: /tmp/hosts.csv

    - name: Read DHCP host data from CSV
      shell: cat /tmp/hosts.csv
      register: csv_data

    - name: Create DHCP host list
      set_fact:
        dhcp_hosts: []

    - name: Process CSV data
      set_fact:
        dhcp_hosts: "{{ dhcp_hosts + [{'hostname': item.split(',')[0], 'ip': item.split(',')[1], 'mac': item.split(',')[2]}] }}"
      loop: "{{ csv_data.stdout_lines[1:] }}"

    - name: Configure DHCP service
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
      notify: Restart DHCP service

    - name: Start and enable DHCP service
      systemd:
        name: dhcpd
        state: started
        enabled: yes
        
  handlers:
    - name: Restart DHCP service
      systemd:
        name: dhcpd
        state: restarted