---
- name: Read Hosts
  hosts: dhcp

  tasks:
  - read_csv:
      path: config.csv
    register: hostlist

  - debug: 
      msg: "{{ host.HOSTNAME }} {{ host.IP }} {{ host.MAC }}"
    loop: "{{ hostlist.list }}"
    loop_control:
      loop_var: host