---

- name: Read Hosts
  gather_facts: True
  hosts: dhcp

  tasks:
  - community.general.read_csv:
      path: config.csv
    register: hostlist

  - debug: 
      msg: "hostname: {{ host.HOSTNAME }} IP:{{ host.IP }} MAC:{{ host.MAC }}"
    loop: "{{ hostlist.list }}"
    loop_control:
      loop_var: host