---
- name: DHCP server installed
  hosts: dhcp

  tasks:
  - name: latest DHCP version installed
    yum:
      name: dhcp
      state: latest

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits DHCP service
    firewalld:
      service: dhcpd
      permanent: true
      state: enabled
      immediate: yes

  - name: DHCP enabled and running
    service:
      name: dhcpd
      enabled: true
      state: started
  
  - read_csv:
      path: config.csv
    register: hostlist
  
  dhcp_hosts:
  - name: {{ host.HOSTNAME }}
    mac: {{ host.MAC }}
    ip: {{ host.IP }}
  loop: "{{ hostlist.list }}"
   loop_control:
   loop_var: host