---

- name: Read Hosts
  gather_facts: True
  hosts: dhcp
  file: config.csv

  tasks:
  - name: Load CSV file
    set_fact:
      hostname: "{{ csvline[0] }}"
      ip_address: "{{ csvline[1] }}"
      mac_address: "{{ csvline[2] }}"
    vars:
      csvline: ¨{{ lookup('csvfile', delimiter=',') }}¨
    delegate_to: localhost

  - debug:
      msg: "{{ hostname }}  {{ ip_address }}  {{ mac_address }}"

