---

- name: Read Hosts
  hosts: dhcp
  
  tasks:
  - read_csv:
        path: config.csv
        key: HOSTNAME
      register: host
    - debug:
        msg: "{{ item.key }}:
              {{ item.value.HOSTNAME }},
              {{ item.value.IP }},
              {{ item.value.MAC }}"
      loop: "{{ host.dict|dict2items }}"

