---

- name: Read Hosts
  gather_facts: True
  hosts: dhcp

  tasks:
  - name: Load CSV file

    debug:
      msg: {{ lookup('csvfile', file='config.csv', delimiter=',') }}



  #  read_csv:
  #    path: config.csv
  #    delimiter: ","
  #  register: hostlist


  #- debug: 
  #    msg: "hostname: {{ host.HOSTNAME }} IP:{{ host.IP }} MAC:{{ host.MAC }}"
  #  loop: "{{ hostlist.list }}"
  #  loop_control:
  #    loop_var: host